### ISSUE TITLE
Is any way to display the dashboard view by default?

### ISSUE THREAD

**Issue by kkkometo** [danielreuther/chroma-theme#11]
i want to display the dashboard view in public view, is any way?

**Comment by kkkometo** [comment]
nevermind,
i change this lines in init_custom.vm and worked

#if ($default_color_scheme)
    #set ($css_class = "${css_class} color-scheme-dashboard")
#else
    #set ($css_class = "${css_class} color-scheme-dashboard")

**Comment by danielreuther** [comment]
Sorry for the (very) late reply. There should be no need to change the code, though. You should be able to choose between dashboard and default by simply selecting the appropriate 'color scheme' in the UI.

**Comment by kkkometo** [comment]
Thanks for your answer , I realized this after a while.
