### ISSUE TITLE
Menu does not work in Nexus 5

### ISSUE THREAD

**Issue by tmoreira2020** [danielreuther/chroma-theme#3]
Hey Daniel, first of all thanks for this awesome theme! Good job man. 
I'm using it to create my wedding website at http://timbaetati.com.br and testing it on my cell phone it breaks the menu. The button does not work eventhough in our Preview section it works. Let me know if you need more input to fix it.

**Comment by danielreuther** [comment]
Hey Thiago,

FIrst, congratulations on the big step you're taking. I wish you all the best :)

The bug itself is bit weird. It looks like our navigation-interaction module errors out because of something. Will let you know once I have a fix for it.

Thanks,
Daniel

**Comment by danielreuther** [comment]
Looks like navigation-interaction-touch doesn't declare all its dependencies (it's missing out on event-outside). I just committed a fix for it.

I'm also planning to push a new version to the marketplace soon—but unfortunately I still have to find a workaround for a bug that made it into the CE GA3 release (LPS-44724).

Thanks again for letting me know about the issue. If there's anyhing else, just let me know :)
Daniel

**Comment by danielreuther** [comment]
Hey Thiago,

Just a quick update, the new version of the theme got approved yesterday—which means the current version on the Marketplace should contain the fix. If you have time to test it, please let me know if it solves the issue.

Thanks,
Danile

**Comment by tmoreira2020** [comment]
Hey Daniel, I made a fork of the project and did a last update in the weekend so I have all the changes in production. There is still one issue related to the menu in a mobile device where the user is not able to click on a submenu. Could you take a look?
Besides that I made some fixes on my fork and turned the project in a Maven project. :smile: Let me know what you think I could open some PRs to you.

**Comment by danielreuther** [comment]
I will take care of the issue regarding the drop downs. I remember having seen a fix in the portal around that problem—I think I'll need to add some markup for this to work.

Your fixes are highly welcome! If you send me the PRs, I'll make sure to merge them in.
I'm also very open to turn it into a Maven project. Could you make that a separate PR, though, so that I can merge that in later? I will need re-organize some things (at least locally move the repo to another location).

Thanks much for using your time to work on this. I personally never thought that this theme would end up being more than a tech demo ;)

Daniel

**Comment by danielreuther** [comment]
@tmoreira2020 I completely forgot to tell you that the drop down issue should (hopefully) be fixed by https://github.com/danielreuther/chroma-theme/commit/991e4571c8aec4ecaf73543cefc3397357e7412f.

**Comment by danielreuther** [comment]
@tmoreira2020 Would you mind if I cherry-picked some commits from your fork? Especially the bug fixes and maybe the Maven-related changes.

Thanks!

**Comment by tmoreira2020** [comment]
Hi Daniel, go ahead e pick wherever you think fits to your project. The
thing is I built everything on top Maven unless you cherry-pick the
mavenized commit the subsequentes won't work.

**Comment by danielreuther** [comment]
Hey Thiago,

Wow. Up until now it didn't occur to me that mavenizing it kind of makes your fork incompatible to my repo. Talk about being oblivious to the obvious...

Anyhow, I planned to switch the project to Maven anyways. Issue solved ;)

Thanks again for your work!
Daniel

**Comment by tmoreira2020** [comment]
Hey Daniel, I just sent a pull request with all the Maven commits, let me
know. Once you accept I can send other pull request with other fixes...
